#!/usr/bin/env node

/**
 * Environment Setup Helper Script
 * 
 * This script helps set up the environment variables for CyberEco platform
 * Run with: node scripts/setup-env.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

// Required environment variables
const requiredVars = [
  {
    key: 'NEXT_PUBLIC_FIREBASE_API_KEY',
    description: 'Firebase API Key',
    example: 'AIzaSyAbc123...'
  },
  {
    key: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
    description: 'Firebase Auth Domain',
    example: 'your-project.firebaseapp.com'
  },
  {
    key: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
    description: 'Firebase Project ID',
    example: 'your-project-id'
  },
  {
    key: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
    description: 'Firebase Storage Bucket',
    example: 'your-project.appspot.com'
  },
  {
    key: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
    description: 'Firebase Messaging Sender ID',
    example: '123456789'
  },
  {
    key: 'NEXT_PUBLIC_FIREBASE_APP_ID',
    description: 'Firebase App ID',
    example: '1:123456789:web:abc123...'
  }
];

async function main() {
  console.log('🚀 CyberEco Environment Setup Helper\n');
  
  const envLocalPath = path.join(process.cwd(), '.env.local');
  const envExamplePath = path.join(process.cwd(), '.env.production.example');
  
  // Check if .env.local already exists
  if (fs.existsSync(envLocalPath)) {
    console.log('✅ .env.local already exists!');
    
    // Check which variables are missing
    const envContent = fs.readFileSync(envLocalPath, 'utf8');
    const missingVars = requiredVars.filter(v => !envContent.includes(v.key));
    
    if (missingVars.length === 0) {
      console.log('✅ All required environment variables are already set!');
      
      const runDev = await question('\nWould you like to start the development server? (y/n): ');
      if (runDev.toLowerCase() === 'y') {
        console.log('\n🏃 Starting development server...');
        console.log('Run: npm run dev\n');
      }
      rl.close();
      return;
    }
    
    console.log(`\n⚠️  Missing ${missingVars.length} required variable(s):`);
    missingVars.forEach(v => console.log(`   - ${v.key}`));
    
    const update = await question('\nWould you like to add the missing variables? (y/n): ');
    if (update.toLowerCase() !== 'y') {
      rl.close();
      return;
    }
  } else {
    // Create new .env.local
    console.log('📝 Creating new .env.local file...\n');
    
    if (fs.existsSync(envExamplePath)) {
      fs.copyFileSync(envExamplePath, envLocalPath);
      console.log('✅ Copied .env.production.example to .env.local\n');
    } else {
      // Create a basic template
      const template = `# CyberEco Environment Variables
# Generated by setup-env.js

${requiredVars.map(v => `# ${v.description}\n${v.key}=\n`).join('\n')}
`;
      fs.writeFileSync(envLocalPath, template);
    }
  }
  
  console.log('📋 Firebase Configuration Setup');
  console.log('================================\n');
  console.log('To get your Firebase configuration:');
  console.log('1. Go to https://console.firebase.google.com/');
  console.log('2. Select your project (or create a new one)');
  console.log('3. Go to Project Settings → General');
  console.log('4. Scroll to "Your apps" and select your web app');
  console.log('5. Copy the configuration values below\n');
  
  const interactive = await question('Would you like to enter the values interactively? (y/n): ');
  
  if (interactive.toLowerCase() === 'y') {
    const values = {};
    
    console.log('\nPlease enter your Firebase configuration values:\n');
    
    for (const variable of requiredVars) {
      const value = await question(`${variable.description} (${variable.key}):\nExample: ${variable.example}\n> `);
      values[variable.key] = value.trim();
      console.log();
    }
    
    // Update .env.local with the values
    let envContent = fs.readFileSync(envLocalPath, 'utf8');
    
    for (const [key, value] of Object.entries(values)) {
      if (value) {
        // Replace the line containing the key
        const regex = new RegExp(`^${key}=.*$`, 'gm');
        if (envContent.match(regex)) {
          envContent = envContent.replace(regex, `${key}=${value}`);
        } else {
          envContent += `\n${key}=${value}`;
        }
      }
    }
    
    fs.writeFileSync(envLocalPath, envContent);
    console.log('✅ Environment variables have been saved to .env.local\n');
    
    // Validate the setup
    const missingAfterUpdate = requiredVars.filter(v => !values[v.key] || values[v.key] === '');
    
    if (missingAfterUpdate.length > 0) {
      console.log('⚠️  The following variables were not set:');
      missingAfterUpdate.forEach(v => console.log(`   - ${v.key}`));
      console.log('\nYou can edit .env.local manually to add these values.\n');
    } else {
      console.log('✅ All required environment variables are set!\n');
      
      const runDev = await question('Would you like to start the development server? (y/n): ');
      if (runDev.toLowerCase() === 'y') {
        console.log('\n🏃 Starting development server...');
        console.log('Run: npm run dev\n');
        console.log('The applications will be available at:');
        console.log('- Hub: http://localhost:40000');
        console.log('- JustSplit: http://localhost:40002');
        console.log('- Website: http://localhost:40001\n');
      }
    }
  } else {
    console.log('\n📝 Please edit .env.local manually with your Firebase configuration.');
    console.log('Each required variable is marked with a comment.\n');
    console.log('Required variables:');
    requiredVars.forEach(v => console.log(`- ${v.key}`));
    console.log('\nOnce done, run: npm run dev');
  }
  
  console.log('\n📚 For more information, see:');
  console.log('- Environment Setup Guide: docs/development/environment-setup.md');
  console.log('- Firebase Security: docs/security/firebase-api-keys.md\n');
  
  rl.close();
}

// Check environment variables (can be used by other scripts)
function checkEnv() {
  const missing = requiredVars.filter(v => !process.env[v.key]);
  
  if (missing.length > 0) {
    console.error('❌ Missing required environment variables:');
    missing.forEach(v => console.error(`   - ${v.key} (${v.description})`));
    console.error('\nRun this script to set up your environment: node scripts/setup-env.js');
    return false;
  }
  
  console.log('✅ All required environment variables are set!');
  return true;
}

// Run the script or export for use in other scripts
if (require.main === module) {
  main().catch(console.error);
} else {
  module.exports = { checkEnv, requiredVars };
}